# Generated by Django 4.1.7 on 2023-04-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_author_author_image_blog_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
