# Generated by Django 4.1.7 on 2023-04-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_slug_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_slug',
            new_name='slug',
        ),
    ]
