# Generated by Django 4.1.7 on 2023-04-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tag',
            new_name='tags',
        ),
    ]
