# Generated by Django 4.1.7 on 2023-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_meta_description_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='google_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
